const CLAN_SEASON_NUM_IN_YEAR_SHIFT = 1 // Because numInYear is zero-based.

enum CLAN_SEASON_MEDAL_TYPE {
  PLACE
  TOP
  RATING
  UNKNOWN
}


return {
  CLAN_SEASON_MEDAL_TYPE
  CLAN_SEASON_NUM_IN_YEAR_SHIFT
}