from "%scripts/dagui_library.nut" import *

let { worldWarMapControls } = require("bhvWorldWarMap.nut")

replace_script_gui_behaviour("worldWarMapControls", worldWarMapControls)

require("%scripts/worldWar/services/wwService.nut")
require("%scripts/worldWar/externalServices/inviteWwOperationBattle.nut")
require("%scripts/worldWar/model/wwUnitType.nut")
require("%scripts/worldWar/inOperation/model/wwOperationArmies.nut")
require("%scripts/worldWar/inOperation/model/wwOperationModel.nut")
require("%scripts/worldWar/inOperation/model/wwAirfield.nut")
require("%scripts/worldWar/inOperation/model/wwArmy.nut")
require("%scripts/worldWar/inOperation/model/wwArmyOwner.nut")
require("%scripts/worldWar/inOperation/model/wwPathTracker.nut")
require("%scripts/worldWar/inOperation/model/wwArtilleryAmmo.nut")
require("%scripts/worldWar/inOperation/model/wwArmyGroup.nut")
require("%scripts/worldWar/inOperation/model/wwUnit.nut")
require("%scripts/worldWar/inOperation/model/wwReinforcementArmy.nut")
require("%scripts/worldWar/inOperation/model/wwOperationLog.nut")
require("%scripts/worldWar/inOperation/view/wwObjectiveView.nut")
require("%scripts/worldWar/inOperation/view/wwBattleResultsView.nut")
require("%scripts/worldWar/inOperation/handler/wwMap.nut")
require("%scripts/worldWar/inOperation/handler/wwObjective.nut")
require("%scripts/worldWar/inOperation/handler/wwOperationLog.nut")
require("%scripts/worldWar/inOperation/handler/wwAirfieldsList.nut")
require("%scripts/worldWar/inOperation/handler/wwArmiesList.nut")
require("%scripts/worldWar/inOperation/handler/wwCommanders.nut")
require("%scripts/worldWar/inOperation/handler/wwReinforcements.nut")
require("%scripts/worldWar/inOperation/handler/wwBattleResults.nut")
require("%scripts/worldWar/operations/model/wwMap.nut")
require("%scripts/worldWar/operations/model/wwOperation.nut")
require("%scripts/worldWar/operations/model/wwOperationsGroup.nut")
require("%scripts/worldWar/operations/handler/wwMapDescription.nut")
require("%scripts/worldWar/operations/handler/wwQueueDescriptionCustomHandler.nut")
require("%scripts/worldWar/operations/handler/wwOperationDescriptionCustomHandler.nut")
require("%scripts/worldWar/operations/handler/wwOperationsListModal.nut")
require("%scripts/worldWar/operations/handler/wwOperationsMapsHandler.nut")
require("%scripts/worldWar/handler/wwMapTooltip.nut")
require("%scripts/worldWar/handler/wwQueueInfo.nut")
require("%scripts/worldWar/handler/wwSquadList.nut")
require("%scripts/worldWar/handler/wwBattleDescription.nut")
require("%scripts/worldWar/handler/wwAirfieldFlyOut.nut")
require("%scripts/worldWar/handler/wwObjectivesInfo.nut")
require("%scripts/worldWar/handler/wwMyClanSquadInviteModal.nut")
require("%scripts/worldWar/handler/wwJoinBattleCondition.nut")
require("%scripts/worldWar/handler/wwLeaderboard.nut")
require("%scripts/worldWar/worldWarRender.nut")
require("%scripts/worldWar/worldWarBattleJoinProcess.nut")
require("%scripts/worldWar/externalServices/matchingNotifications/worldwar.nut")
require("%scripts/worldWar/worldWarUtils.nut")
require("%scripts/worldWar/debugTools/dbgUtils.nut")


require("%scripts/worldWar/wwPromo.nut")
require("%scripts/worldWar/wwSquadManager.nut")
require("%scripts/worldWar/wwInvites.nut")
require("%scripts/worldWar/wwInviteOperation.nut")
require("%scripts/worldWar/wwOperationChatRoomType.nut")
require("%scripts/worldWar/wwGenericTooltipTypesInit.nut")
