enum EVENT_TYPE { 
  UNKNOWN         = 0
  SINGLE          = 1,
  CLAN            = 2,
  TOURNAMENT      = 4,
  NEWBIE_BATTLES  = 8,

  
  ANY             = 15,
  ANY_BASE_EVENTS = 5,
}

enum UnitRelevance {
  NONE,
  MEDIUM,
  BEST,
}

enum GAME_EVENT_TYPE {
  
  TM_NONE = "TM_NONE"

  
  TM_NONE_RACE = "TM_NONE_RACE"

  
  TM_ELO_PERSONAL = "TM_ELO_PERSONAL"
  TM_ELO_GROUP = "TM_ELO_GROUP"
  TM_ELO_GROUP_DETAIL = "TM_ELO_GROUP_DETAIL"
  TM_DOUBLE_ELIMINATION = "TM_DOUBLE_ELIMINATION"
}


return {
  UnitRelevance
  EVENT_TYPE
  EVENTS_SHORT_LB_VISIBLE_ROWS = 3
  GAME_EVENT_TYPE
}