
require("%scripts/items/itemsClasses/itemAttachable.nut")
require("%scripts/items/itemsClasses/itemBattlePass.nut")
require("%scripts/items/itemsClasses/itemBooster.nut")
require("%scripts/items/itemsClasses/itemChest.nut")
require("%scripts/items/itemsClasses/itemCraftPart.nut")
require("%scripts/items/itemsClasses/itemCraftProcess.nut")
require("%scripts/items/itemsClasses/itemDecal.nut")
require("%scripts/items/itemsClasses/itemDiscount.nut")
require("%scripts/items/itemsClasses/itemEntitlement.nut")
require("%scripts/items/itemsClasses/itemInternalItem.nut")
require("%scripts/items/itemsClasses/itemKey.nut")
require("%scripts/items/itemsClasses/itemModOverdrive.nut")
require("%scripts/items/itemsClasses/itemModUpgrade.nut")
require("%scripts/items/itemsClasses/itemOrder.nut")
require("%scripts/items/itemsClasses/itemProfileIcon.nut")
require("%scripts/items/itemsClasses/itemRecipesBundle.nut")
require("%scripts/items/itemsClasses/itemRentedUnit.nut")
require("%scripts/items/itemsClasses/itemSkin.nut")
require("%scripts/items/itemsClasses/itemSmoke.nut")
require("%scripts/items/itemsClasses/itemTicket.nut")
require("%scripts/items/itemsClasses/itemTrophy.nut")
require("%scripts/items/itemsClasses/itemUnitCouponMod.nut")
require("%scripts/items/itemsClasses/itemUniversalSpare.nut")
require("%scripts/items/itemsClasses/itemUnlock.nut")
require("%scripts/items/itemsClasses/itemVehicle.nut")
require("%scripts/items/itemsClasses/itemWager.nut")
require("%scripts/items/itemsClasses/itemWarbonds.nut")
require("%scripts/items/itemsClasses/itemWarpoints.nut")

require("%scripts/items/itemsClasses/itemGenerators.nut")

