//for load and register all items classes
require("itemAttachable.nut")
require("itemBattlePass.nut")
require("itemBooster.nut")
require("itemChest.nut")
require("itemCraftPart.nut")
require("itemCraftProcess.nut")
require("itemDecal.nut")
require("itemDiscount.nut")
require("itemEntitlement.nut")
require("itemInternalItem.nut")
require("itemKey.nut")
require("itemModOverdrive.nut")
require("itemModUpgrade.nut")
require("itemOrder.nut")
require("itemProfileIcon.nut")
require("itemRecipesBundle.nut")
require("itemRentedUnit.nut")
require("itemSkin.nut")
require("itemSmoke.nut")
require("itemTicket.nut")
require("itemTrophy.nut")
require("itemUnitCouponMod.nut")
require("itemUniversalSpare.nut")
require("itemUnlock.nut")
require("itemVehicle.nut")
require("itemWager.nut")
require("itemWarbonds.nut")
require("itemWarpoints.nut")

require("itemGenerators.nut")

