let expEventConsts = require_optional("expEventConsts")
let consttable = getconsttable()

let fields = [
  "EXP_EVENT_LANDING",
  "EXP_EVENT_TAKEOFF",
  "EXP_EVENT_CAPTURE_ZONE",
  "EXP_EVENT_DESTROY_ZONE",
  "EXP_EVENT_SIGHT",
  "EXP_EVENT_KILL",
  "EXP_EVENT_KILL_GROUND",
  "EXP_EVENT_SESSION_AWARD",
  "EXP_EVENT_ROUND_AWARD",
  "EXP_EVENT_CRITICAL_HIT",
  "EXP_EVENT_KILL_BY_TEAM",
  "EXP_EVENT_INSURANCE_RETURN",
  "EXP_EVENT_HIT",
  "EXP_EVENT_ASSIST",
  "EXP_EVENT_BATTLETIME",
  "EXP_EVENT_STREAK",
  "EXP_EVENT_DAMAGE_ZONE",
  "EXP_EVENT_OVERKILL",
  "EXP_EVENT_BATTLETROPHY",
  "EXP_EVENT_INEFFECTIVE_HIT",
  "EXP_EVENT_RESPAWN",
  "EXP_EVENT_OBJECTIVE",
  "EXP_EVENT_RACE_FINISHED",
  "EXP_EVENT_UNIT_DAMAGE",
  "EXP_EVENT_SCOUT",
  "EXP_EVENT_SCOUT_CRITICAL_HIT",
  "EXP_EVENT_SCOUT_KILL",
  "EXP_EVENT_SCOUT_KILL_UNKNOWN",
  "EXP_EVENT_TIMED_AWARD",
  "EXP_EVENT_DEATH",
  "EXP_EVENT_MISSION_ACTION",
  "EXP_EVENT_HELP_TO_ALLIES",
  "EXP_EVENT_EXPENSES_COMPENSATION",
  "EXP_EVENT_SKILL_BONUS",
  "EXP_EVENT_SEVERE_DAMAGE",
  "EXP_EVENT_MISSILE_EVADE",
  "EXP_EVENT_SHELL_INTERCEPTION",
  "EXP_EVENT_RETURN_SPAWN_COST",
  "EXP_EVENT_KILL_HUMAN",
  "EXP_EVENT_TOTAL",
]

let export = {}
foreach (k in fields)
  export[k] <- expEventConsts?[k] ?? consttable[k]

return freeze(export)
