let shopItemConsts = require_optional("shopItemConsts")
let consttable = getconsttable()

let fields = [
  "ES_ITEM_STATUS_LOCKED",
  "ES_ITEM_STATUS_CAN_RESEARCH",
  "ES_ITEM_STATUS_IN_RESEARCH",
  "ES_ITEM_STATUS_CAN_BUY",
  "ES_ITEM_STATUS_OWNED",
  "ES_ITEM_STATUS_MOUNTED",
  "ES_ITEM_STATUS_RESEARCHED",
  "EIT_BOOSTER",
  "EIT_ORDER",
  "EIT_WAGER",
  "EIT_TOURNAMENT_TICKET",
  "EIT_PERSONAL_DISCOUNTS",
  "EIT_Blueprint",
  "EIT_UNIVERSAL_SPARE",
  "EIT_MOD_OVERDRIVE",
  "EIT_MOD_UPGRADE",
  "EIT_TOTAL",
  "ORDER_USE_RESULT_OK",
  "ORDER_USE_RESULT_BAD_MODE",
  "ORDER_USE_RESULT_BAD_PLAYER",
  "ORDER_USE_RESULT_NO_ITEM",
  "ORDER_USE_RESULT_ORDER_RUNNING",
  "ORDER_USE_RESULT_COOLDOWN",
  "ORDER_USE_RESULT_BAD_ITEM_CONFIG",
  "ORDER_USE_RESULT_MAX_USES",
  "ORDER_USE_RESULT_ALREADY_USED",
  "ORDER_USE_RESULT_MODE_SPECIFIC_ERROR",
  "EWBAT_INVALID",
  "EWBAT_UNIT",
  "EWBAT_ITEM",
  "EWBAT_TROPHY",
  "EWBAT_SKIN",
  "EWBAT_DECAL",
  "EWBAT_ATTACHABLE",
  "EWBAT_WP",
  "EWBAT_GOLD",
  "EWBAT_BATTLE_TASK",
  "EWBAT_EXT_INVENTORY_ITEM",
]

let export = {}
foreach (k in fields)
  export[k] <- shopItemConsts?[k] ?? consttable[k]

return freeze(export)
