const MAX_PLAYERS_VERSUS = 64

enum BATTLE_TYPES {
  AIR      = 0,
  TANK     = 1,
  SHIP     = 2,
}

const BATTLE_TYPES_ORDER = [BATTLE_TYPES.AIR, BATTLE_TYPES.TANK, BATTLE_TYPES.SHIP]

return {
  BATTLE_TYPES
  BATTLE_TYPES_ORDER
  MAX_PLAYERS_VERSUS
}