return {
  EII_BULLET = 0
  EII_ARTILLERY_TARGET = 1
  EII_ANTI_AIR_TARGET = 2
  EII_EXTINGUISHER = 3
  EII_SPECIAL_UNIT = 4
  EII_WINCH = 5
  EII_WINCH_DETACH = 6
  EII_WINCH_ATTACH = 7
  EII_TOOLKIT = 8
  EII_MEDICALKIT = 9

  EII_TORPEDO = 10
  EII_TORPEDO_SIGHT = 11
  EII_HULL_AIMING = 12
  EII_DEPTH_CHARGE = 13
  EII_MINE = 14
  EII_ROCKET = 15
  EII_GRENADE = 16
  EII_SMOKE_GRENADE = 17
  EII_REPAIR_BREACHES = 18
  EII_SMOKE_SCREEN = 19

  EII_SCOUT = 20
  EII_SUBMARINE_SONAR = 21
  EII_TORPEDO_SENSOR = 22
  EII_SHIP_CURRENT_TRIGGER_GROUP = 23
  EII_MORTAR = 24
  WEAPON_PRIMARY = 25
  WEAPON_SECONDARY = 26
  WEAPON_MACHINEGUN = 27
  EII_FORCED_GUN = 28
  EII_SPEED_BOOSTER = 29
  EII_AI_GUNNERS = 30
  EII_AUTO_TURRET = 31
  EII_SUPPORT_PLANE = 32
  EII_SUPPORT_PLANE_2 = 33
  EII_SUPPORT_PLANE_ORBITING = 34
  EII_SUPPORT_PLANE_CHANGE = 35
  EII_SUPPORT_PLANE_GROUP_ATTACK = 36
  EII_STEALTH = 37
  EII_LOCK = 38
  EII_WEAPON_LEAD = 39
  EII_TERRAFORM = 40
  EII_DIVING_LOCK = 41
  EII_SHIP_DAMAGE_CONTROL = 42
  EII_NIGHT_VISION = 43
  EII_SIGHT_STABILIZATION = 44
  //





  AI_GUNNERS_DISABLED = 0
  AI_GUNNERS_ALL_TARGETS = 1
  AI_GUNNERS_AIR_TARGETS = 2
  AI_GUNNERS_GROUND_TARGETS = 3
  AI_GUNNERS_SHELL = 4

  GUIDANCE_LEAD_MODE_AUTO = 0
  GUIDANCE_LEAD_MODE_OFF = 1
  GUIDANCE_LEAD_MODE_ON = 2
}
