



const SQUAD_LEAVE_REQUESTED = "SquadLeaveRequested"
const SQUAD_REVOKE_ALL_INVITES_REQUESTED = "SquadRevokeAllInvitesRequested"
const SQUAD_SET_READY_REQUESTED = "SquadSetReadyRequested"
const SQUAD_SET_CREWS_READY_REQUESTED = "SquadSetCrewsReadyRequested"
const SQUAD_MY_MEMBER_DATA_UPDATE_REQUESTED = "SquadMyMemberDataUpdateRequested"
const SQUAD_JOIN_REQUESTED = "SquadJoinRequested"
const MATCHING_EVENTS_DATA_RECEIVED = "MatchingEventsDataReceived"
const LEADER_GAME_MODE_APPLIED = "LeaderGameModeApplied"


const BATTLE_RATING_CHANGED = "BattleRatingChanged"
const EVENTS_DATA_UPDATED = "EventsDataUpdated"
const INVENTORY_UPDATE = "InventoryUpdate"
const GAME_LOCALIZATION_CHANGED = "GameLocalizationChanged"
const CHAT_JOIN_ROOM = "ChatJoinRoom"
const CHAT_LEAVE_SQUAD_ROOM = "ChatLeaveSquadRoom"

return freeze({
  SQUAD_LEAVE_REQUESTED
  SQUAD_REVOKE_ALL_INVITES_REQUESTED
  SQUAD_SET_READY_REQUESTED
  SQUAD_SET_CREWS_READY_REQUESTED
  SQUAD_MY_MEMBER_DATA_UPDATE_REQUESTED
  SQUAD_JOIN_REQUESTED
  MATCHING_EVENTS_DATA_RECEIVED
  LEADER_GAME_MODE_APPLIED
  BATTLE_RATING_CHANGED
  EVENTS_DATA_UPDATED
  INVENTORY_UPDATE
  GAME_LOCALIZATION_CHANGED
  CHAT_JOIN_ROOM
  CHAT_LEAVE_SQUAD_ROOM
})
