<<#items>>
shopFilter
{
  size:t='@mIco, @mIco'
  tooltip:t='<<tooltip>>'
  shopFilterImg
  {
    id:t='<<imgId>>'
    background-image:t='<<imgBg>>'
  }
  discount_notification
  {
    id:t='<<discountId>>';
    type:t='box_left';
    noShift:t='yes';
    text:t='';
    tooltip:t=''
  }
}
<</items>>
