::dagor.debug($"onScriptLoadAfterLogin: wt")
require("controls/shortcutsList/updateShortcutsModulesList.nut")
require("mainmenu/onMainMenuReturn.nut")
require("mainmenu/instantActionHandler.nut")
require("mainmenu/mainMenuHandler.nut")
require("hud/updateHudConfig.nut")
