let countryToCluster = {
  AM = "RU" // Armenia
  AZ = "RU" // Azerbaijan
  BY = "RU" // Belarus
  BG = "RU" // Bulgaria
  HR = "RU" // Croatia
  EE = "RU" // Estonia
  FI = "RU" // Finland
  GE = "RU" // Georgia
  HU = "RU" // Hungary
  KZ = "RU" // Kazakhstan
  KG = "RU" // Kyrgyzstan
  LV = "RU" // Latvia
  LT = "RU" // Lithuania
  MD = "RU" // Moldova
  PL = "RU" // Poland
  RU = "RU" // Russia
  SK = "RU" // Slovakia
  SI = "RU" // Slovenia
  SE = "RU" // Sweden
  TM = "RU" // Turkmenistan
  UA = "RU" // Ukraine
  UZ = "RU" // Uzbekistan
  AF = "RU" // Afghanistan
  BH = "RU" // Bahrain
  BD = "RU" // Bangladesh
  BT = "RU" // Bhutan
  BN = "RU" // Brunei
  KH = "RU" // Cambodia
  CX = "RU" // Christmas Island
  CC = "RU" // Cocos Islands
  IO = "RU" // Diego Garcia
  HK = "RU" // Hong Kong
  ID = "RU" // Indonesia
  IR = "RU" // Iran
  IQ = "RU" // Iraq
  IL = "RU" // Israel
  JO = "RU" // Jordan
  KW = "RU" // Kuwait
  LB = "RU" // Lebanon
  MV = "RU" // Maldives
  OM = "RU" // Oman
  PK = "RU" // Pakistan
  PS = "RU" // Palestine
  QA = "RU" // Qatar
  SA = "RU" // Saudi Arabia
  SY = "RU" // Syria
  TJ = "RU" // Tajikistan
  TR = "RU" // Turkey
  AE = "RU" // United Arab Emirates
  YE = "RU" // Yemen

  AL = "EU" // Albania
  AD = "EU" // Andorra
  AT = "EU" // Austria
  BE = "EU" // Belgium
  BA = "EU" // Bosnia
  CY = "EU" // Cyprus
  CZ = "EU" // Czech Republic
  DK = "EU" // Denmark
  FO = "EU" // Faroe Islands
  FR = "EU" // France
  DE = "EU" // Germany
  GI = "EU" // Gibraltar
  GR = "EU" // Greece
  IS = "EU" // Iceland
  IE = "EU" // Ireland
  IM = "EU" // Isle of Man
  IT = "EU" // Italy
  RS = "RU" // Serbia
  LI = "EU" // Liechtenstein
  LU = "EU" // Luxembourg
  MK = "EU" // Macedonia
  MT = "EU" // Malta
  MC = "EU" // Monaco
  ME = "EU" // Montenegro
  NL = "EU" // Netherlands
  NO = "EU" // Norway
  PT = "EU" // Portugal
  RO = "EU" // Romania
  SM = "EU" // San Marino
  ES = "EU" // Spain
  CH = "EU" // Switzerland
  GB = "EU" // United Kingdom
  VA = "EU" // Vatican city

  AR = "US" // Argentina
  BO = "US" // Bolivia
  BR = "US" // Brazil
  CL = "US" // Chile
  CO = "US" // Colombia
  EC = "US" // Ecuador
  FK = "US" // Falkland Islands
  GF = "US" // French Guiana
  GY = "US" // Guyana
  PY = "US" // Paraguay
  PE = "US" // Peru
  SR = "US" // Suriname
  UY = "US" // Uruguay
  VE = "US" // Venezuela
  AI = "US" // Anguilla
  AG = "US" // Antigua and Barbuda
  AW = "US" // Aruba
  BS = "US" // Bahamas
  BB = "US" // Barbados
  BZ = "US" // Belize
  BM = "US" // Bermuda
  VG = "US" // British Virgin Islands
  CA = "US" // Canada
  KY = "US" // Cayman Islands
  CR = "US" // Costa Rica
  CU = "US" // Cuba
  CW = "US" // Curacao
  DM = "US" // Dominica
  DO = "US" // Dominican Republic
  SV = "US" // El Salvador
  GL = "US" // Greenland
  GD = "US" // Grenada and Carriacuou
  GP = "US" // Guadeloupe
  GT = "US" // Guatemala
  HT = "US" // Haiti
  HN = "US" // Honduras
  JM = "US" // Jamaica
  MQ = "US" // Martinique
  MX = "US" // Mexico
  MS = "US" // Montserrat
  KN = "US" // Saint Kitts and Nevis
  NI = "US" // Nicaragua
  PA = "US" // Panama
  PR = "US" // Puerto Rico
  BQ = "US" // Saba, Sint Eustatius, Bonaire
  SX = "US" // Sint Maarten
  LC = "US" // St. Lucia
  PM = "US" // St. Pierre and Miquelon
  VC = "US" // St. Vincent
  TT = "US" // Trinidad and Tobago
  TC = "US" // Turks and Caicos Islands
  VI = "US" // US Virgin Islands
  US = "US" // United States
  AS = "US" // American Samoa
  AU = "SA;US" // Australia
  NZ = "SA;US" // New Zealand
  CK = "US" // Cook Islands
  TL = "US" // East Timor
  FM = "US" // Federated States of Micronesia
  FJ = "US" // Fiji Islands
  PF = "US" // French Polynesia
  GU = "US" // Guam
  KI = "US" // Kiribati
  MP = "US" // Northern Mariana Islands
  MH = "US" // Marshall Islands
  UM = "US" // United States Minor Outlying Islands
  NR = "US" // Nauru
  NC = "US" // New Caledonia
  NU = "US" // Niue
  NF = "US" // Norfolk Island
  PW = "US" // Palau
  PG = "US" // Papua New Guinea
  WS = "US" // Samoa
  SB = "US" // Solomon Islands
  TK = "US" // Tokelau
  TO = "US" // Tonga
  TV = "US" // Tuvalu
  VU = "US" // Vanuatu
  WF = "US" // Wallis and Futuna Islands

  CN = "SA" // China
  IN = "SA" // India
  JP = "SA" // Japan
  LA = "SA" // Laos
  MO = "SA" // Macau
  MY = "SA" // Malaysia
  MN = "SA" // Mongolia
  MM = "SA" // Myanmar
  NP = "SA" // Nepal
  KP = "SA" // North Korea
  PH = "SA" // Philippines
  SG = "SA" // Singapore
  KR = "SA" // South Korea
  LK = "SA" // Sri Lanka
  TW = "SA" // Taiwan
  TH = "SA" // Thailand
  VN = "SA" // Vietnam
}

let getClustersByCountry = @(code) countryToCluster?[code].split_by_chars(";", true) ?? []

return {
  getClustersByCountry
}
